name: CI

on:
  workflow_dispatch:
      inputs:
        test-level:
          type: choice
          description: Specify test level of deployment
          options: 
            - RunLocalTests
            - NoTestRun

run-name: Salesforce CI/CD ${{ github.ref_name }} by ${{ github.actor }} 

concurrency: concurrency-1

jobs:
  job-1:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Comment PR
        run: sleep 100


        
      


