# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:

env:
  myNull: ${{ null }}
  myString: ${{ 'Abc' }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Read myString
        run: | 
          echo $myString
          echo ${{ env.myString }}
