name: CI

on:
  workflow_dispatch:

env:
  myNull: ${{ null }}
  myBoolean: ${{ false }}
  myIntegerNumber: ${{ 711 }}
  myFloatNumber: ${{ -9.2 }}
  myString: ${{ 'Mona the Octocat' }}
  
jobs:
  first_job:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Read Variable
        run:  | 
          echo ${{ env.myString }}
          echo $myString
      - name: Read Variable 2
        env:
          myString: DEF
        run:  | 
          echo ${{ env.myString }}
          
      - name: Read context variables
        run: |
          echo '${{ toJson(github) }}'
          echo '${{ toJson(job) }}'
          echo '${{ toJson(secrets) }}'
          echo '${{ toJson(steps) }}'
          echo '${{ toJson(runner) }}'
          
      


