name: CI

on:
  pull_request:

run-name: Salesforce CI/CD ${{ github.ref_name }} by ${{ github.actor }} 
 
concurrency: 
  group: ${{ github.event.inputs.salesforce-environment }}
  cancel-in-progress: true

jobs:
  job-1:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Hello world ! :wave:



        
      


