# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:

env:
  myNull: ${{ null }}
  myString: ${{ 'Abc' }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      myString: ${{ 'Cde' }}
    steps:
      - name: Step 1
        run: Sleep 40
      - name: Failure
        if: failure()
        run: echo "Failure"
      - name: Success
        # default
        if: success()
        run: echo "Success"
      - name: Always
        if: always()
        run: echo "Always"
      - name: Cancel
        if: cancelled()
        run: echo "Cancelled"
  job-2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Step1
        run: echo 'Job-2'
          

