
name: CI


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

env:
  TEST_LEVEL: NoTest

jobs:
  first_job:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Read Variable
        run: echo "API_URL ${{ vars.API_URL }}"
      - name: Read Secret
        run: echo "API_TOKEN ${{ secrets.API_TOKEN }}"
      - name: Nonexisting Secret
        run: echo "API_TOKEN ${{ secrets.NON_EXISTING_API_TOKEN }}"
      - name: Github provided variable
        run: echo "Repostiory ${{ github.repository }}"
      - name: Env variable
        if: failure()
        run: echo "ENV ${{ env.TEST_LEVEL }} LUB $TEST_LEVEL"


