name: CI

on:
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Fail
        id: step-2
        run: exit 1
      - name: Step 1
        run: sleep 20
      - name: Runs on Failure
        if: failure() && steps.step-2.conclusion == 'failure'
        run: echo 'Failure'
      - name: Runs on Success
        #default behaviour
        if: success()
        run: echo 'Runs on Success'
      - name: Runs Always
        if: always()
        run: echo 'Always'
      - name: Runs when Cancelled
        if: cancelled()
        run: echo 'Cancelled'

  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    steps:
      - name: Step 1
        run: echo 'Job-2'
      
        
      


