# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:

env:
  myNull: ${{ null }}
  myString: ${{ 'Abc' }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      myString: ${{ 'Cde' }}
    steps:
      - name: Set Variable
        run: | 
          echo "newString=Hello" >> "$GITHUB_ENV"
          echo "myString=GEF" >> "$GITHUB_ENV"
          MESSAGE=ZXC
          echo "MESSAGE=$MESSAGE" >> "$GITHUB_ENV"
          echo "CURRENT_DATE=$(date)" >> "$GITHUB_ENV"
      - name: Read Variables
        run: | 
          echo $newString
          echo $myString
          echo $MESSAGE
          echo ${{ env.MESSAGE }} 
          echo $CURRENT_DATE
          
          

