# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:

env:
  myNull: ${{ null }}
  myString: ${{ 'Abc' }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      myString: ${{ 'Cde' }}
    steps:
      - name: Read myString
        env:
          myString: ${{ 'Def' }}
        run: | 
          echo $myString
          echo ${{ env.myString }}
      - name: Read myString 2
        run: | 
          echo $myString
          echo ${{ env.myString }}

