# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:

env:
  myNull: ${{ null }}
  myString: ${{ 'Abc' }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Read myString
        run: | 
          echo $myString
          echo ${{ env.myString }}

      - name: Step 2
        if: env.myString == 'Abc'
        run: | 
          echo '${{ toJson(github) }}'
          echo '${{ toJson(job) }}'
          echo '${{ toJson(secrets) }}'
          echo '${{ toJson(env) }}'
          echo '${{ toJson(steps) }}'
          echo '${{ toJson(runner) }}'
