
name: CI


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:


jobs:
  first_job:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo First Job!


