name: CI

on:
  workflow_dispatch:
      inputs:
        test-level:
          type: choice
          description: Specify test level of deployment
          options: 
            - RunLocalTests
            - NoTestRun

run-name: Salesforce CI/CD ${{ github.ref_name }} by ${{ github.actor }} 

jobs:
  job-1:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Set variable
        id: color-selector
        run: |
          echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
      - name: Read variables
        run: |
          echo ${{ steps.color-selector.outputs.SELECTED_COLOR }}

        
      


