name: CI

on:
  workflow_dispatch:

env:
  myNull: ${{ null }}
  myBoolean: ${{ false }}
  myIntegerNumber: ${{ 711 }}
  myFloatNumber: ${{ -9.2 }}
  myString: ${{ 'ABC' }}
  
jobs:
  first_job:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Read Variable
        if: $myString == 'ABC'
        run:  | 
          echo ${{ env.myString }}
          echo $myString
      - name: Read Variable 2
        env:
          myString: DEF
        run:  | 
          echo ${{ env.myString }}

      - name: Set Up Variable
        run: |
          echo "newString=Hello" >> "$GITHUB_ENV"
          echo "myString=GHJ" >> "$GITHUB_ENV"
          MESSAGE='1234'
          echo "MESSAGE=$MESSAGE" >> "$GITHUB_ENV"
          echo "CURRENT_DATE=$(date)" >> "$GITHUB_ENV"
          
      - name: Read Variable
        run:  | 
          echo ${{ env.myString }}
          echo ${{ env.MESSAGE }}
          echo ${{ env.CURRENT_DATE }}
          
      - name: Read context variables
        run: |
          echo '${{ toJson(github) }}'
          echo '${{ toJson(job) }}'
          echo '${{ toJson(secrets) }}'
          echo '${{ toJson(steps) }}'
          echo '${{ toJson(runner) }}'
          
      


