# This is a basic workflow to help you get started with Actions

name: CI

run-name: Salesforce CI/CD ${{ github.ref_name }} by ${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      test-level:
        type: choice
        description: Specify test level of deployment
        options: 
          - RunLocalTests
          - NoTestRun

env:
  myNull: ${{ null }}
  myString: ${{ 'Abc' }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    env:
      myString: ${{ 'Cde' }}
    steps:
      - name: Step 1
        run: sleep 90
      - name: Failure
        if: failure() && steps.step-1.conclusion == 'failure'
        run: echo "Failure"
      - name: Success
        # default
        if: success()
        run: echo "Success"
      - name: Always
        if: success() || failure()
        run: echo "Always"
      - name: Cancel
        if: cancelled()
        run: echo "Cancelled"
  job-2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Step1
        run: echo 'Job-2'
          

