name: Matrix Workflow

on: 
   workflow_dispatch:

jobs:
   node-matrix:
      strategy:
         matrix:
            os: [ubuntu-latest, windows-latest]
            node-version: [14, 15]
            include:
               - color: green
               - color: red
                 os: ubuntu-latest
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/setup-node@v3
          with:
             node-version: ${{ matrix.node-version }}
        - run:  node -v
        - run: echo '123'
          if: matrix.color == 'green'
