name: Matrix Workflow

on: 
   workflow_dispatch:

# { os: ubuntu-latest, node-version: 14 }
# { os: ubuntu-latest, node-version: 15 }
# { os: windows-latest, node-version: 14 }
# { os: windows-latest, node-version: 15 }

jobs:
   node-matrix:
      strategy:
         matrix:
            os: [ubuntu-latest, windows-latest]
            node-version: [14, 15]
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/setup-node@v3
          with:
             node-version: ${{ matrix.node-version }}
        - run:  node -v
        - run: echo '123'
          if: matrix.color == 'green'
