name: Reusable Workflow
on:
  workflow_call:
    inputs:
      color:
        description: "Input description"
        type: string
        default: "Abc"
        required: false

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -a
  log-context-and-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Dispay Github Context
        run: echo '${{ toJSON(github) }}'
      - name: Display color input
        run: echo ${{ inputs.color }}

